### ISSUE TITLE
PacBio Software versions

### ISSUE THREAD

**Issue by rotifergirl** [makovalab-psu/nonBKinetics#1]
Hi! 
Thanks so much for these detailed notes. I'm trying to run a similar analysis to look at G4s, but I've run into a problem. I have all my PacBio reads aligned to my assembly, split by chromosome, and sorted, but then when I went to use ipdSummary, I got an error that it does not accept *.cmp.h5 files. This was with kineticsTools v3.0 downloaded this week from PacBio's github.

Could you tell me which version of ipdSummary you were using? And potentially where to find it?

Thanks so much!
Julie Blommaert

**Comment by wilfriedguiblet** [comment]
Hello!

Yes, the new version of kineticTools does not read .h5 format anymore. You would have to use the version smrtanalysis-2.3.0. It should be available here: 

https://www.pacb.com/support/software-downloads/

Are you using an older sequencing project with .h5 files? PacBio now outputs .bam files. This may help: 

https://pacbiofileformats.readthedocs.io/en/9.0/

Please let me know if you have more questions,
Wilfried Guiblet

**Comment by rotifergirl** [comment]
Thanks for this response! It's not overly clear to me which part of smrtanalysis-2.3.0 I should be using? The only mention I can find of IPDs is under a heading called "P_ModificationDetection Module" here https://smrt-analysis.readthedocs.io/en/latest/SMRT-Pipe-Reference-Guide-v2.3.0/

The data I have are RSII chemistry, but I only recently generated the .h5 files while following the steps in this github. Should I re-do the mappings to produce .bam files then?

**Comment by wilfriedguiblet** [comment]
If I understand correctly what is your problem, you need to use ipdsummary.py and input the alignment in .cmp.h5 format.

If it is not too much a hassle, I would recommend you to use the .bam format and the last version of the software. Working on legacy software may bring further issues.

Hope this helps

**Comment by rotifergirl** [comment]
Thanks! I have tried using the ipdsummary.py tool now, but it seems there is an issue with the installation of the SMRT analysis tools on our cluster. 

Thanks for your help so far! I will close this issue now, but will let you know when everything works 😊
